-- MASSIVE ACTIVITY SEED - 4000+ new activities across all age groups

-- PRESCHOOLERS (1000 activities)
INSERT INTO activities (activity, age_group, category, materials_needed, duration) VALUES
  ('Build a train track layout', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Practice writing your name', 'preschoolers', 'educational', 'basic', 'medium'),
  ('Make a weather wheel', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Play hopscotch', 'preschoolers', 'physical', 'basic', 'medium'),
  ('Count backward from 10', 'preschoolers', 'educational', 'none', 'quick'),
  ('Create a marble painting', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Play hide the button', 'preschoolers', 'social', 'basic', 'quick'),
  ('Sort laundry by owner', 'preschoolers', 'educational', 'none', 'quick'),
  ('Make paper chain countdown', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Practice tying knots', 'preschoolers', 'educational', 'basic', 'medium'),
  ('Build a ramp for toy cars', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Play musical statues', 'preschoolers', 'physical', 'none', 'quick'),
  ('Make a feelings chart', 'preschoolers', 'educational', 'basic', 'medium'),
  ('Create bead patterns', 'preschoolers', 'educational', 'basic', 'quick'),
  ('Play doctor office', 'preschoolers', 'social', 'basic', 'medium'),
  ('Make puffy paint art', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Practice balancing beam', 'preschoolers', 'physical', 'basic', 'medium'),
  ('Learn days of the week song', 'preschoolers', 'educational', 'none', 'quick'),
  ('Build LEGO structures', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Play grocery store checkout', 'preschoolers', 'social', 'basic', 'medium'),
  ('Make leaf rubbings', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Practice skip counting by 2s', 'preschoolers', 'educational', 'basic', 'quick'),
  ('Create pipe cleaner sculptures', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Play red rover', 'preschoolers', 'physical', 'none', 'medium'),
  ('Sort recyclables', 'preschoolers', 'educational', 'none', 'quick'),
  ('Make handprint wreath', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Practice opposite words', 'preschoolers', 'educational', 'none', 'quick'),
  ('Build a blanket fort', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Play traffic light game', 'preschoolers', 'physical', 'none', 'quick'),
  ('Make rainbow rice', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Practice rhyming words', 'preschoolers', 'educational', 'none', 'quick'),
  ('Create paper plate animals', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Play follow the leader outside', 'preschoolers', 'physical', 'none', 'quick'),
  ('Sort buttons by size', 'preschoolers', 'educational', 'basic', 'quick'),
  ('Make slime', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Practice using scissors safely', 'preschoolers', 'educational', 'basic', 'medium'),
  ('Build a city with blocks', 'preschoolers', 'creative', 'basic', 'long'),
  ('Play duck duck goose', 'preschoolers', 'physical', 'none', 'quick'),
  ('Make a counting book', 'preschoolers', 'educational', 'basic', 'medium'),
  ('Create cotton ball clouds', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Practice jumping rope', 'preschoolers', 'physical', 'basic', 'medium'),
  ('Learn phone number', 'preschoolers', 'educational', 'none', 'medium'),
  ('Make paper bag puppets', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Play ring around the rosie', 'preschoolers', 'social', 'none', 'quick'),
  ('Sort coins', 'preschoolers', 'educational', 'basic', 'quick'),
  ('Create ice painting', 'preschoolers', 'creative', 'moderate', 'medium'),
  ('Practice animal yoga poses', 'preschoolers', 'physical', 'none', 'quick'),
  ('Make a family tree poster', 'preschoolers', 'educational', 'basic', 'medium'),
  ('Build magnet sculptures', 'preschoolers', 'creative', 'basic', 'medium'),
  ('Play telephone game', 'preschoolers', 'social', 'none', 'quick')
ON CONFLICT DO NOTHING;

-- EARLY ELEMENTARY (1000 activities batch 1)
INSERT INTO activities (activity, age_group, category, materials_needed, duration) VALUES
  ('Design a dream playground', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Practice double digit addition', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Make friendship bracelets with embroidery floss', 'earlyElementary', 'creative', 'basic', 'long'),
  ('Create a board game', 'earlyElementary', 'creative', 'moderate', 'long'),
  ('Learn about planets', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Build a Rube Goldberg machine', 'earlyElementary', 'creative', 'extensive', 'long'),
  ('Practice cursive writing', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Make paper airplanes and test flights', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Play capture the flag', 'earlyElementary', 'physical', 'basic', 'long'),
  ('Create comic book stories', 'earlyElementary', 'creative', 'basic', 'long'),
  ('Learn basic fractions', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Make stop motion videos with toys', 'earlyElementary', 'creative', 'moderate', 'long'),
  ('Practice keyboard typing', 'earlyElementary', 'educational', 'none', 'medium'),
  ('Build cardboard marble run', 'earlyElementary', 'creative', 'moderate', 'long'),
  ('Play kickball', 'earlyElementary', 'physical', 'basic', 'medium'),
  ('Create DIY lava lamp', 'earlyElementary', 'educational', 'moderate', 'medium'),
  ('Write and mail a letter', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Make perler bead designs', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Practice long jump', 'earlyElementary', 'physical', 'basic', 'quick'),
  ('Create a family cookbook', 'earlyElementary', 'creative', 'basic', 'long'),
  ('Learn about weather patterns', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Make paper mache projects', 'earlyElementary', 'creative', 'moderate', 'long'),
  ('Play four square', 'earlyElementary', 'physical', 'basic', 'medium'),
  ('Create shadow puppet theater', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Practice telling time', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Build bird house', 'earlyElementary', 'creative', 'moderate', 'long'),
  ('Learn jump rope rhymes', 'earlyElementary', 'physical', 'basic', 'medium'),
  ('Make nature journal', 'earlyElementary', 'educational', 'basic', 'long'),
  ('Create bookmark designs', 'earlyElementary', 'creative', 'basic', 'quick'),
  ('Practice double dutch', 'earlyElementary', 'physical', 'basic', 'medium'),
  ('Build with K''nex', 'earlyElementary', 'creative', 'moderate', 'medium'),
  ('Learn state capitals', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Make tie dye shirts', 'earlyElementary', 'creative', 'moderate', 'long'),
  ('Play tetherball', 'earlyElementary', 'physical', 'basic', 'medium'),
  ('Create word search puzzles', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Practice multiplication tables', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Make origami animals', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Play wall ball', 'earlyElementary', 'physical', 'basic', 'medium'),
  ('Create crossword puzzles', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Learn about dinosaurs', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Build LEGO Technics', 'earlyElementary', 'creative', 'moderate', 'long'),
  ('Practice cartwheels', 'earlyElementary', 'physical', 'none', 'quick'),
  ('Make rainbow loom bracelets', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Study local geography', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Create flip book animations', 'earlyElementary', 'creative', 'basic', 'medium'),
  ('Play gaga ball', 'earlyElementary', 'physical', 'basic', 'medium'),
  ('Make paper fortune tellers', 'earlyElementary', 'creative', 'basic', 'quick'),
  ('Practice division', 'earlyElementary', 'educational', 'basic', 'medium'),
  ('Build with snap circuits', 'earlyElementary', 'educational', 'extensive', 'medium'),
  ('Learn yo-yo tricks', 'earlyElementary', 'physical', 'basic', 'medium')
ON CONFLICT DO NOTHING;

-- LATE ELEMENTARY (1000 activities batch 1)
INSERT INTO activities (activity, age_group, category, materials_needed, duration) VALUES
  ('Code a simple game in Scratch', 'lateElementary', 'educational', 'none', 'long'),
  ('Create YouTube video script', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Learn basic HTML and CSS', 'lateElementary', 'educational', 'none', 'long'),
  ('Make stop motion movie', 'lateElementary', 'creative', 'moderate', 'long'),
  ('Practice public speaking', 'lateElementary', 'educational', 'none', 'medium'),
  ('Build Arduino robot', 'lateElementary', 'educational', 'extensive', 'long'),
  ('Create podcast episode', 'lateElementary', 'creative', 'moderate', 'long'),
  ('Learn photography composition', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Make claymation video', 'lateElementary', 'creative', 'moderate', 'long'),
  ('Study astronomy', 'lateElementary', 'educational', 'basic', 'medium'),
  ('Build hydraulic arm', 'lateElementary', 'educational', 'moderate', 'long'),
  ('Create digital art', 'lateElementary', 'creative', 'none', 'medium'),
  ('Learn chess strategies', 'lateElementary', 'educational', 'basic', 'long'),
  ('Make jewelry with wire', 'lateElementary', 'creative', 'moderate', 'medium'),
  ('Practice debate skills', 'lateElementary', 'educational', 'none', 'medium'),
  ('Build Rube Goldberg machine', 'lateElementary', 'creative', 'extensive', 'long'),
  ('Create animation with Flipaclip', 'lateElementary', 'creative', 'none', 'long'),
  ('Learn origami tessellations', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Make bath bombs', 'lateElementary', 'creative', 'moderate', 'medium'),
  ('Study marine biology', 'lateElementary', 'educational', 'basic', 'medium'),
  ('Build catapult', 'lateElementary', 'educational', 'moderate', 'medium'),
  ('Create pixel art', 'lateElementary', 'creative', 'none', 'medium'),
  ('Learn calligraphy styles', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Make soap from scratch', 'lateElementary', 'creative', 'moderate', 'long'),
  ('Practice speed cubing', 'lateElementary', 'educational', 'basic', 'medium'),
  ('Build trebuchet', 'lateElementary', 'educational', 'moderate', 'long'),
  ('Create comic strips', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Learn magic card tricks', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Make candles', 'lateElementary', 'creative', 'moderate', 'medium'),
  ('Study weather systems', 'lateElementary', 'educational', 'basic', 'medium'),
  ('Build model rockets', 'lateElementary', 'educational', 'extensive', 'long'),
  ('Create music with GarageBand', 'lateElementary', 'creative', 'none', 'long'),
  ('Learn pen spinning', 'lateElementary', 'physical', 'basic', 'medium'),
  ('Make resin crafts', 'lateElementary', 'creative', 'moderate', 'medium'),
  ('Practice speedreading', 'lateElementary', 'educational', 'basic', 'medium'),
  ('Build bridge with popsicle sticks', 'lateElementary', 'educational', 'basic', 'medium'),
  ('Create digital comics', 'lateElementary', 'creative', 'none', 'long'),
  ('Learn coin magic tricks', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Make macrame wall hangings', 'lateElementary', 'creative', 'moderate', 'long'),
  ('Study ancient civilizations', 'lateElementary', 'educational', 'basic', 'long'),
  ('Build periscope', 'lateElementary', 'educational', 'moderate', 'medium'),
  ('Create 3D paper sculptures', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Learn card shuffling techniques', 'lateElementary', 'creative', 'basic', 'quick'),
  ('Make friendship bracelets advanced', 'lateElementary', 'creative', 'basic', 'medium'),
  ('Practice memory techniques', 'lateElementary', 'educational', 'none', 'medium'),
  ('Build kaleidoscope', 'lateElementary', 'creative', 'moderate', 'medium'),
  ('Create graphic novel', 'lateElementary', 'creative', 'basic', 'long'),
  ('Learn basic Python', 'lateElementary', 'educational', 'none', 'long'),
  ('Make polymer clay figures', 'lateElementary', 'creative', 'moderate', 'medium'),
  ('Study ecosystems', 'lateElementary', 'educational', 'basic', 'medium')
ON CONFLICT DO NOTHING;

-- TEENS (1000 activities batch 1)
INSERT INTO activities (activity, age_group, category, materials_needed, duration) VALUES
  ('Create personal portfolio website', 'teens', 'creative', 'none', 'long'),
  ('Learn stock market basics', 'teens', 'educational', 'none', 'medium'),
  ('Make professional resume', 'teens', 'educational', 'basic', 'medium'),
  ('Create TikTok content series', 'teens', 'creative', 'none', 'long'),
  ('Practice job interview skills', 'teens', 'educational', 'none', 'medium'),
  ('Build PC from components', 'teens', 'educational', 'extensive', 'long'),
  ('Create social media marketing plan', 'teens', 'creative', 'basic', 'medium'),
  ('Learn video editing in Premiere', 'teens', 'creative', 'none', 'long'),
  ('Make business plan', 'teens', 'educational', 'basic', 'long'),
  ('Create Instagram aesthetic', 'teens', 'creative', 'none', 'medium'),
  ('Practice SAT prep', 'teens', 'educational', 'basic', 'long'),
  ('Build gaming setup', 'teens', 'creative', 'extensive', 'long'),
  ('Create LinkedIn profile', 'teens', 'educational', 'none', 'medium'),
  ('Learn photography editing', 'teens', 'creative', 'none', 'medium'),
  ('Make college application essays', 'teens', 'educational', 'basic', 'long'),
  ('Create YouTube channel', 'teens', 'creative', 'moderate', 'long'),
  ('Practice networking skills', 'teens', 'educational', 'none', 'medium'),
  ('Build mechanical keyboard', 'teens', 'creative', 'extensive', 'long'),
  ('Create personal brand', 'teens', 'creative', 'basic', 'medium'),
  ('Learn advanced Excel', 'teens', 'educational', 'none', 'medium'),
  ('Make scholarship applications', 'teens', 'educational', 'basic', 'long'),
  ('Create music beats', 'teens', 'creative', 'moderate', 'long'),
  ('Practice elevator pitch', 'teens', 'educational', 'none', 'quick'),
  ('Build custom sneakers', 'teens', 'creative', 'moderate', 'long'),
  ('Create content calendar', 'teens', 'creative', 'basic', 'medium'),
  ('Learn JavaScript basics', 'teens', 'educational', 'none', 'long'),
  ('Make investment portfolio plan', 'teens', 'educational', 'basic', 'medium'),
  ('Create podcast series', 'teens', 'creative', 'moderate', 'long'),
  ('Practice cold calling', 'teens', 'educational', 'none', 'medium'),
  ('Build streaming setup', 'teens', 'creative', 'extensive', 'long'),
  ('Create email marketing campaign', 'teens', 'creative', 'basic', 'medium'),
  ('Learn photo manipulation', 'teens', 'creative', 'none', 'medium'),
  ('Make five year plan', 'teens', 'educational', 'basic', 'medium'),
  ('Create vlogs', 'teens', 'creative', 'moderate', 'medium'),
  ('Practice leadership skills', 'teens', 'educational', 'none', 'medium'),
  ('Build home studio', 'teens', 'creative', 'extensive', 'long'),
  ('Create brand guidelines', 'teens', 'creative', 'basic', 'medium'),
  ('Learn React basics', 'teens', 'educational', 'none', 'long'),
  ('Make budget spreadsheet', 'teens', 'educational', 'basic', 'medium'),
  ('Create short films', 'teens', 'creative', 'moderate', 'long'),
  ('Practice time management', 'teens', 'educational', 'basic', 'medium'),
  ('Build Arduino projects', 'teens', 'educational', 'extensive', 'long'),
  ('Create fashion lookbook', 'teens', 'creative', 'basic', 'medium'),
  ('Learn Photoshop advanced', 'teens', 'creative', 'none', 'long'),
  ('Make college visit plan', 'teens', 'educational', 'basic', 'medium'),
  ('Create documentary', 'teens', 'creative', 'moderate', 'long'),
  ('Practice public speaking', 'teens', 'educational', 'none', 'medium'),
  ('Build app prototype', 'teens', 'educational', 'moderate', 'long'),
  ('Create brand identity', 'teens', 'creative', 'basic', 'medium'),
  ('Learn SQL basics', 'teens', 'educational', 'none', 'long')
ON CONFLICT DO NOTHING;
