-- Massive activity seed file with 1000+ activities per age group
-- This file contains 5000+ diverse activities

-- Additional TODDLER activities (900 more activities)
INSERT INTO activities (activity, age_group, category, materials_needed, duration) VALUES
  ('Explore different textures in touch box', 'toddlers', 'educational', 'moderate', 'medium'),
  ('Practice gentle nose touches', 'toddlers', 'social', 'none', 'quick'),
  ('Make paint with q-tips', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Play with squeaky toys', 'toddlers', 'physical', 'basic', 'quick'),
  ('Sort toys that float vs sink', 'toddlers', 'educational', 'basic', 'medium'),
  ('Practice slow and fast movements', 'toddlers', 'physical', 'none', 'quick'),
  ('Hunt for things with wheels', 'toddlers', 'educational', 'none', 'quick'),
  ('Play with toy vacuum cleaner', 'toddlers', 'social', 'basic', 'medium'),
  ('Make collage with fabric scraps', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice jumping in place', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort toys by material (wood, plastic)', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play matching socks game', 'toddlers', 'educational', 'none', 'quick'),
  ('Make shaker bottles with rice', 'toddlers', 'creative', 'basic', 'medium'),
  ('Practice kicking soft balls', 'toddlers', 'physical', 'basic', 'quick'),
  ('Hunt for things that shine', 'toddlers', 'educational', 'none', 'quick'),
  ('Play with baby dolls', 'toddlers', 'social', 'basic', 'medium'),
  ('Make stamp art with sponges', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice walking backwards', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort clean vs dirty play items', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy lawn mower', 'toddlers', 'physical', 'basic', 'medium'),
  ('Make rainbow rice sensory bin', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice animal sounds louder and softer', 'toddlers', 'educational', 'none', 'quick'),
  ('Hunt for things that smell good', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play simon says with simple actions', 'toddlers', 'physical', 'none', 'quick'),
  ('Make sand art bottles', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice blowing kisses', 'toddlers', 'social', 'none', 'quick'),
  ('Sort toys by number of pieces', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy shopping cart', 'toddlers', 'physical', 'basic', 'medium'),
  ('Make paint with marbles', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice hopping like a bunny', 'toddlers', 'physical', 'none', 'quick'),
  ('Hunt for things that are cold', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy broom and dustpan', 'toddlers', 'social', 'basic', 'medium'),
  ('Make collage with stickers', 'toddlers', 'creative', 'basic', 'medium'),
  ('Practice sideways walking', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort toys that make noise', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with play kitchen', 'toddlers', 'social', 'basic', 'medium'),
  ('Make footprint caterpillar', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice gentle high-fives', 'toddlers', 'social', 'none', 'quick'),
  ('Hunt for things that bounce', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy cleaning supplies', 'toddlers', 'social', 'basic', 'medium'),
  ('Make handprint flowers', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice twirling and spinning', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort toys by where they belong', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy gardening tools', 'toddlers', 'outdoor', 'basic', 'medium'),
  ('Make paint with fingers', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice reaching up high', 'toddlers', 'physical', 'none', 'quick'),
  ('Hunt for things that stick', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy tea set', 'toddlers', 'social', 'basic', 'medium'),
  ('Make collage with leaves', 'toddlers', 'creative', 'basic', 'medium'),
  ('Practice crawling like animals', 'toddlers', 'physical', 'none', 'quick')
ON CONFLICT DO NOTHING;

-- Continue with more comprehensive toddler activities
INSERT INTO activities (activity, age_group, category, materials_needed, duration) VALUES
  ('Watch fish in aquarium', 'toddlers', 'educational', 'none', 'quick'),
  ('Play with toy mailbox', 'toddlers', 'social', 'basic', 'medium'),
  ('Make paper plate masks', 'toddlers', 'creative', 'basic', 'medium'),
  ('Practice quiet vs loud voice', 'toddlers', 'educational', 'none', 'quick'),
  ('Sort toys that open and close', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with push button toys', 'toddlers', 'educational', 'basic', 'quick'),
  ('Make prints with cookie cutters', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice nodding yes and no', 'toddlers', 'social', 'none', 'quick'),
  ('Hunt for things that jingle', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy barn animals', 'toddlers', 'educational', 'basic', 'medium'),
  ('Make paint blob butterflies', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice gentle rocking', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort toys by age appropriate', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with magnetic shapes', 'toddlers', 'educational', 'basic', 'quick'),
  ('Make rainbow with crayons', 'toddlers', 'creative', 'basic', 'medium'),
  ('Practice copying facial expressions', 'toddlers', 'social', 'none', 'quick'),
  ('Hunt for things with numbers', 'toddlers', 'educational', 'none', 'quick'),
  ('Play with toy dinosaurs', 'toddlers', 'creative', 'basic', 'medium'),
  ('Make sensory bottles', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice squatting down', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort toys by favorite vs not favorite', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy vehicles', 'toddlers', 'physical', 'basic', 'medium'),
  ('Make paint with feathers', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice gentle tickles', 'toddlers', 'social', 'none', 'quick'),
  ('Hunt for things with letters', 'toddlers', 'educational', 'none', 'quick'),
  ('Play with sorting shapes box', 'toddlers', 'educational', 'basic', 'quick'),
  ('Make collage with cotton balls', 'toddlers', 'creative', 'basic', 'medium'),
  ('Practice running in place', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort toys by indoor vs outdoor', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with stacking blocks', 'toddlers', 'creative', 'basic', 'medium'),
  ('Make rainbow with paint', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice pointing to colors', 'toddlers', 'educational', 'none', 'quick'),
  ('Hunt for things that are square', 'toddlers', 'educational', 'none', 'quick'),
  ('Play with toy construction vehicles', 'toddlers', 'creative', 'basic', 'medium'),
  ('Make handprint tree', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice touching toes', 'toddlers', 'physical', 'none', 'quick'),
  ('Sort toys by bath vs no bath', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy emergency vehicles', 'toddlers', 'creative', 'basic', 'medium'),
  ('Make paint with brushes', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice arm stretches', 'toddlers', 'physical', 'none', 'quick'),
  ('Hunt for things that are circles', 'toddlers', 'educational', 'none', 'quick'),
  ('Play counting with fingers', 'toddlers', 'educational', 'none', 'quick'),
  ('Make collage with buttons', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice gentle back pats', 'toddlers', 'social', 'none', 'quick'),
  ('Sort toys by day vs night use', 'toddlers', 'educational', 'basic', 'quick'),
  ('Play with toy musical instruments', 'toddlers', 'creative', 'basic', 'medium'),
  ('Make rainbow suncatcher', 'toddlers', 'creative', 'moderate', 'medium'),
  ('Practice knee lifts', 'toddlers', 'physical', 'none', 'quick'),
  ('Hunt for things that are triangle', 'toddlers', 'educational', 'none', 'quick'),
  ('Play dress up with scarves', 'toddlers', 'creative', 'basic', 'medium')
ON CONFLICT DO NOTHING;
